### ISSUE TITLE
Improve spinner naming

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/cli-spinners#1]
[Naming is hard.](http://martinfowler.com/bliki/TwoHardThings.html) I could use some help improving the name of each spinner. Especially those that are numbered should preferably be split up into something more unique.

https://github.com/sindresorhus/cli-spinners/blob/master/spinners.json

**Comment by derhuerst** [comment]
Consider a naming consistent with [*spin*](https://github.com/fishery/spin).

**Comment by sindresorhus** [comment]
@derhuerst Thanks, I renamed (https://github.com/sindresorhus/cli-spinners/commit/89d129a338b8f3f2e21544886c44a551d028b257) a few of them. Still open for suggestion for the rest.

**Comment by rootulp** [comment]
Proposed spinner name changes:
- `grow: ["▁", "▃", "▄", "▅", "▆", "▇", "▆", "▅", "▄", "▃"]` -> `growVertical`
- `grow2: ["▏", "▎", "▍", "▌", "▋", "▊", "▉", "▊", "▋", "▌", "▍", "▎"]` -> `growHorizontal`
- `spin: ["◰", "◳", "◲", "◱"]` -> `spinCorners` or `corners`
- `spin2: ["◴", "◷", "◶", "◵"]` -> `spinQuarters` or `quarters`
- `spin3: ["◐", "◓", "◑", "◒"]` -> `spinHalves` or `halves`
- `spin4: ["╫", "╪"]` -> `squish`
- `bouncing: ["[    ]", "[   =]", "[  ==]", "[ ===]", "[====]", "[=== ]", "[==  ]", "[=   ]"]` -> `bouncingBar` to match with `bouncingBall`

**Comment by sindresorhus** [comment]
Maybe:

`corners` => `squareCorners`
`quarters` => `circleQuarters`
`halves` => `circleHalves`

?

**Comment by rootulp** [comment]
Seems reasonable! I'll work on the changes.
