### ISSUE TITLE
Binary missing?

### ISSUE THREAD

**Issue by chauncey-garrett** [sindresorhus/cli-spinners#15]
Should there be a binary link for the cli version?

```json
  "bin": {
    "spinners": "index.js"
  },
```

**Comment by kevva** [comment]
This repo is just a JSON with a list of CLI spinners meant to be used by other CLI tools (like [ora](https://github.com/sindresorhus/ora)).

**Comment by chauncey-garrett** [comment]
Thanks for the clarification!
