### ISSUE TITLE
I followed the guide, but it's just loading the object array

### ISSUE THREAD

**Issue by Ev1dentFir3** [sindresorhus/cli-spinners#21]
Like the title says. Are there other dependencies for getting this to work? I'm still kind of new to js.

**Comment by SamVerschueren** [comment]
Use Ora for terminal spinners https://github.com/sindresorhus/ora

**Comment by Ev1dentFir3** [comment]
usage.js
```java
const cliSpinners = require('cli-spinners');

console.log(cliSpinners.dots);
```
console output
```
null: Object {interval: 80, frames: Array(10)}
null: 
```
Is this dependent on using ora?

**Comment by kevva** [comment]
You should use [sindresorhus/ora](https://github.com/sindresorhus/ora) instead of this module if you want to display the spinner.

**Comment by Ev1dentFir3** [comment]
fair enough, thanks
