### ISSUE TITLE
Extra space after emoji spinners in macOS High Sierra Terminal

### ISSUE THREAD

**Issue by mvila** [sindresorhus/cli-spinners#24]
In the Terminal, since macOS High Sierra there is one more space after emoji spinners:

![screenshot](https://s3.amazonaws.com/mvila/images/cli-spinners-screenshot.png)

**Comment by sindresorhus** [comment]
I've [seen this issue before](https://github.com/sindresorhus/cli-spinners/pull/23#discussion_r1425986060). It seems to be a problem with Terminal.app as it looks correct on iTerm.

**Comment by mvila** [comment]
Well, I think it's a deliberate choice from Apple. Before, an emoji was visually consuming two columns but we needed to add a space after to avoid character overlapping. Now, these extra spaces are no longer necessary, which makes more sense maybe.

**Comment by sindresorhus** [comment]
But according to https://github.com/sindresorhus/cli-spinners/pull/23#discussion_r1425986060, it's not applied consistently for all emojis.

**Comment by mvila** [comment]
Hmm, it's going to be very messy then... 😕

**Comment by sindresorhus** [comment]
Closing as there's not much we can do about this.
