### ISSUE TITLE
marquee spinner feature?

### ISSUE THREAD

**Issue by joeycozza** [sindresorhus/cli-spinners#30]
![marqueespinner](https://user-images.githubusercontent.com/3885959/37304588-9eb783d8-25f7-11e8-81e2-1a4443be7acc.gif)

So my use case was to make a little scrolling marquee, which was fine and very easy to hard code the frames how I wanted (for use in ora).

But I was wondering if it would be a useful addition to have a marquee spinner, where it would take a given text, and then generate the frames needed to make it scroll like a marquee. 

If others would like something like this, I'd be more than willing to make it and submit the PR. 
If you think it doesn't really matter and that people can just make their own marquee by hand like I did, then that's cool too. You can just close this issue then.

Thanks for the great tools sindresorhus.

*Edit: The marquee should probably scroll the other way...

**Comment by sindresorhus** [comment]
I like the idea, but I don't think it's a good fit here. All the current spinners are static and each spinner is exposed as a property. Exposing a function would break that convention.

I would recommend publishing it as a module with a default export that accepts the text and the width and returns a `cli-spinners` compatible object: `{interval: 80, frames: […]}`. I would be happy to link to it in the Ora readme if you decide to make it.
