### ISSUE TITLE
Make `example-all.js` show each spinner the same amount of time

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/cli-spinners#4]
Currently it only shows each frame of a spinner, which is fine for those with many frames, but this doesn't work very well for spinners with few frames. Ideally it should show each spinner equally long.

A pull request would be appreciated :)

https://github.com/sindresorhus/cli-spinners/blob/055d22444bfb7bc718853c2183c8750402ebd2d9/example-all.js

**Comment by dbkaplun** [comment]
Maybe it should only show the next spinner when the user presses a key?

**Comment by sindresorhus** [comment]
I like the idea of skipping to the next one when pressing <kbd>Enter</kbd> or something, but it should still switch every second.

**Comment by axelstudios** [comment]
I put together a demo page to show them all at once - it definitely helped me visualize the options.  You're welcome to do anything like with this:

https://jsfiddle.net/axelstudios/patt152y/

**Comment by sindresorhus** [comment]
@axelstudios Great idea. I've added a link to it in the readme.

**Comment by sindresorhus** [comment]
Closing this as we have the nice JSFiddle by @​axelstudios.
