### ISSUE TITLE
support for deno

### ISSUE THREAD

**Issue by KeJunMao** [sindresorhus/cli-spinners#45]
Hi, do you have any plans to add support for `deno`? :)
I tried, it seems very simple, just create `mod.ts`.
Can I create a PR for this?

https://github.com/sindresorhus/cli-spinners/compare/master...KeJunMao:master

```bash
# example-all
deno run https://raw.githubusercontent.com/KeJunMao/cli-spinners/master/example-all.ts
# example args[0] spinnersType
deno run https://raw.githubusercontent.com/KeJunMao/cli-spinners/master/example.ts dots
```
> `deno` does not support importing JSON

**Comment by sindresorhus** [comment]
There's is a JS file Deno could import: https://github.com/sindresorhus/cli-spinners/blob/master/index.js

I'm not interested in adding special handling for Deno. Deno should support the existing ecosystem.
