### ISSUE TITLE
Switch from json to js

### ISSUE THREAD

**Issue by nnmrts** [sindresorhus/cli-spinners#51]
Kind of inspired by #42, I figured it would be nice if the spinners file would be in js, so theoretical extremely long spinners could be written programmatically. Sure, one would lose the ability to use the json file everywhere, but honestly the advantages of using js here seem bigger than that one disadvantage.

**Comment by sindresorhus** [comment]
I would prefer to keep it JSON. If you have any need for programmatic creation, it could be added to a JS file that also imports the JSON.

**Comment by nnmrts** [comment]
The json file is getting quite big though. Small changes to a single spinner changes the whole file. If we would switch to js, we could modularize all of them. Also, if this project ever moves to ESM, we would have to `fs.readFile` the json because json imports aren't working (yet (and probably not in the next few years)). And, practically, how would something like #42 be solved? Should programmatic spinners be added by creating a new js file somewhere before importing it in [index.js](https://github.com/sindresorhus/cli-spinners/blob/main/index.js) and adding it to imported `cliSpinners` object?

I mean, it's your decision, I respect that and it's not that big of a deal after all, but maybe #53 will change your mind? 😄

**Comment by sindresorhus** [comment]
The benefit of keeping it JSON is that other projects, even in other languages can easily make use of this. For example, [this](https://github.com/manrajgrover/py-spinners/blob/a73d561aa58b12afc3aa4ee80143dca87656688d/spinners/spinners.py) and [this](https://github.com/FGRibreau/spinners/blob/7017a5b251b3c78cdea21b13f21e9cd21b7099e4/src/spinners_data.rs).

Yes, the JSON is large, but I rather optimize for ease of use for end-users than a little inconvenience for editing the file.

---

> Also, if this project ever moves to ESM, we would have to fs.readFile the json because json imports aren't working (yet (and probably not in the next few years))

True, but it's very likely JSON modules will happen in the next year, not two. And this package can just wait.

> And, practically, how would something like #42 be solved? Should programmatic spinners be added by creating a new js file somewhere before importing it in index.js and adding it to imported the cliSpinners object?

The main export would be `index.js`. That file would contain the programmatic spinners, but also import and merge the JSON file.

**Comment by nnmrts** [comment]
Alright, it was worth the try. 😄 Gonnna close this and the PR.
