### ISSUE TITLE
2.6.1 broke semver contract

### ISSUE THREAD

**Issue by thejustinwalsh** [sindresorhus/cli-spinners#57]
I am a bit confused by the results I am seeing between v2.6.0 and v2.6.1, the changes seem simple enough, yet I am having an issue with ink-spinners now that cli-spinners resolves to version 2.6.1..

```
 ERROR  Cannot read property 'hamburger' of undefined

 node_modules/ink-spinner/build/index.js:12:43

  9:  */
 10: const Spinner = ({ type = 'dots' }) => {
 11:     const [frame, setFrame] = react_1.useState(0);
 12:     const spinner = cli_spinners_1.default[type];
 13:     react_1.useEffect(() => {
 14:         const timer = setInterval(() => {
 15:             setFrame(previousFrame => {
```

If I force a resolution to cli-spinners 2.6.0, this error goes away, if it installes 2.6.1 I get this error every time.... 🤷

**Comment by vadimdemedes** [comment]
Update to `ink-spinner@4.0.3` to fix this.

**Comment by thejustinwalsh** [comment]
Thanks!

I still think that version 2.6.1 was not a patch because it broke the contract of the exports, and that 2.6.1 should be republished without the removal of the default export, then a new version with the removal of the default export should be pushed, and I may argue that this change would require a major version bump.

**Comment by sindresorhus** [comment]
Yes, I agree this should have been handled better. But this is super old now and it doesn't make sense to do anything more about this, so I'm going to close.
