### ISSUE TITLE
Missing `main` field

### ISSUE THREAD

**Issue by AndrewLeedham** [sindresorhus/cli-spinners#61]
Hi. I was curious if the `main` field was not included purposefully? It seems to be causing issues with `typescript@next`'s ESM handling, as it is a little more strict on where it looks for types. That is experimental behaviour so I just wanted to open the discussion of adding a `main` field as that should not cause issues for CJS or ESM but will fix the type resolution from `ora` when using `typescript@next` alonside the new `"module": "nodenext"` option.

**Comment by sindresorhus** [comment]
`main` is not required for CJS if the package has a file named `index.js`. Any issues with this is something you should take up with the TypeScript project. Lots of packages follow this convention. The right place to fix it is in TS.
