### ISSUE TITLE
ERR_REQUIRE_ESM; cant import ora

### ISSUE THREAD

**Issue by klm127** [sindresorhus/cli-spinners#66]
Using typescript with CommonJS modules.

Can't `import` ora regularly or with dynamic import
```
Error [ERR_REQUIRE_ESM]: require() of ES Module ...\node_modules\ora\index.js from path/to/myfile.js not supported.
Instead change the require of index.js in path/to/myfile.js to a dynamic import() which is available in all CommonJS modules.
```
```
  code: 'ERR_REQUIRE_ESM'
```
node v 20.1

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by klm127** [comment]
> https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

Thank you. I guess the problem actually originates in https://github.com/sindresorhus/log-update which ora ultimately depends on, but you already know that.

I followed your guide, but wasn't able to get things working with typescript after a decent amount of fiddling, and I dropped the dependency all together and just wrote it myself.

It has me scratching my head because I *always* use `import x from "the/path"`. My impression now is that Typescript doesn't really fully support ESM? Guess I still don't really understand the problem.

If you had a few tips for Typescript for an ignoramus like myself, it'd make me a lot more likely to figure out the ESM issue and join you ESM adopters.

Thanks again for the info.

**Comment by damusix** [comment]
There are literally no decent spinner packages that work with commonjs anymore lmao, man... this is very lame.

**Comment by mainrs** [comment]
> There are literally no decent spinner packages that work with commonjs anymore lmao, man... this is very lame.

You're free to fork the project and port it back to CommonJS. It hasa permissive license.

**Comment by damusix** [comment]
@mainrs If I made you a build script, could you publish it as `cli-sinners-cjs` and put is as part of your pipelines? It'd be nice to not leave an entire majority of users out.
