### ISSUE TITLE
create an asciicast

### ISSUE THREAD

**Issue by derhuerst** [sindresorhus/cli-spinners#8]
Compared to a GIF, an [asciicast](https://asciinema.org/) has a few advantages:

- It can be paused.
- It is a lot smaller than a GIF showing 50 spinners.
- It can be copied & pasted.
- It could be generated automatically on every release/push using an npm script.

I'd love to contribute an asciicast to the readme.

**Comment by sindresorhus** [comment]
That's a great idea. PR most welcome :)

**Comment by derhuerst** [comment]
@sindresorhus Is it on purpose that `example-all.js` has no abort logic? It just fails by exception once all spinners have been shown. Not very nice to show in an asciicast :smile:

**Comment by derhuerst** [comment]
@sindresorhus I could create an NPM script that records and uploads everything, but [`asciinema`](https://github.com/asciinema/asciinema) is a non-NPM dependency. Shall I create it anyway?

**Comment by sindresorhus** [comment]
> Is it on purpose that example-all.js has no abort logic? It just fails by exception once all spinners have been shown.

I threw that file together in 5 min. I'm sure it could be improved in many ways. Happy to see improvements to it ;)

> I could create an NPM script that records and uploads everything, but asciinema is a non-NPM dependency. Shall I create it anyway?

Yeah, sure. As long as it works by me just having the `asciinema` $PATH, I'm happy.

**Comment by derhuerst** [comment]
Done as of #12.
